//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intermedia
    {
        public Nullable<int> id_sala { get; set; }
        public Nullable<int> id_asiento { get; set; }
        public int id_intermedia { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
