//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pelicula()
        {
            this.Proyecciones = new HashSet<Proyeccione>();
        }
    
        public int id_pelicula { get; set; }
        public int id_clasifacion { get; set; }
        public string nombre_pelicula { get; set; }
        public string duracion_pelicula { get; set; }
        public int id_genero { get; set; }
        public string imagen_pelicula { get; set; }
    
        public virtual Clasificacion Clasificacion { get; set; }
        public virtual Genero Genero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyeccione> Proyecciones { get; set; }
    }
}
