//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pelicula()
        {
            this.Proyeccion = new HashSet<Proyeccion>();
        }
    
        public int id_pelicula { get; set; }
        public int id_clasifacion { get; set; }
        public string nombre_pelicula { get; set; }
        public string duracion_pelicula { get; set; }
        public int id_genero { get; set; }
        public string imagen_pelicula { get; set; }
        public int id_formato { get; set; }
    
        public virtual Clasificacion Clasificacion { get; set; }
        public virtual Formato Formato { get; set; }
        public virtual Genero Genero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proyeccion> Proyeccion { get; set; }
    }
}
