//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyeccione
    {
        public int id_proyeccion { get; set; }
        public Nullable<int> id_sala { get; set; }
        public Nullable<int> id_pelicula { get; set; }
        public Nullable<int> id_formato { get; set; }
        public string hora { get; set; }
    
        public virtual Formato Formato { get; set; }
        public virtual Pelicula Pelicula { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
