//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int id_reserva { get; set; }
        public Nullable<int> id_asiento { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string estado_reserva { get; set; }
    
        public virtual Asiento Asiento { get; set; }
    }
}
