//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string nombre { get; set; }
        public string Password { get; set; }
        public string mail { get; set; }
        public string phone { get; set; }
        public string apellidos { get; set; }
        public string tarjeta { get; set; }
        public Nullable<int> id_rol { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
